# Generated by Django 4.0.6 on 2022-08-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitaisEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20, verbose_name='estado')),
                ('capital', models.CharField(max_length=20, verbose_name='capital')),
                ('habitantes', models.IntegerField(verbose_name='habitantes')),
            ],
        ),
    ]
