# Generated by Django 4.0.6 on 2022-08-05 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitaisestados',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
